import { Client, Intents, TextChannel, } from 'discord.js';
import { getRegexPatternFileName } from './author_switch_logic';
import { iterateRegPatternsAsyncEmbeds as iterateRegPatternsCheckingRedirectUrl, iterateRegPatternsAsyncString, iteratePatternsSynchronousEmbeds } from './embed_listener';
import { logger } from './logger';
import { getTweetShiftAuthor } from './utils';

var client: Client = new Client({
    intents: [
        Intents.FLAGS.GUILDS, // todo remove unnecessary Intents
        Intents.FLAGS.GUILD_MEMBERS,
        Intents.FLAGS.GUILD_EMOJIS_AND_STICKERS,
        Intents.FLAGS.GUILD_INTEGRATIONS,
        Intents.FLAGS.GUILD_WEBHOOKS,
        Intents.FLAGS.DIRECT_MESSAGES,
        Intents.FLAGS.GUILD_MESSAGES, // in theory this is the only intent that is needed
        Intents.FLAGS.GUILD_PRESENCES
    ]
});
// todo move regex list to in-memory to speed up execution

client.on('messageCreate', (message: any): void => { // todo test race condition with large volumes of tweets triggering simultaneously
    if (message.author.id === client.user?.id) return; // Doesn't trigger on self 
    if (!message.author.bot) return; // Ignores messages that aren't from bots
    logger.info('received new message to parse from', message.author, new Date())
    logger.info(`message content`, message)

    const lastMessage = (message.channel as TextChannel)?.lastMessage; // can't directly take message as an embed generated by link will not appear in messageCreate events
    const messageAuthor = getTweetShiftAuthor(message);
    const messageConfigFile = getRegexPatternFileName(messageAuthor);

    if (lastMessage?.embeds) {
        const embeds: any[] = lastMessage.embeds;
        const matchRes = iteratePatternsSynchronousEmbeds(embeds, messageConfigFile, client);
        if (matchRes == "NO MATCH") iterateRegPatternsCheckingRedirectUrl(embeds, true, messageConfigFile, client);
    }
    else { // execute logic for raw string messages
        if (lastMessage?.content) iterateRegPatternsAsyncString(lastMessage?.content, messageConfigFile, client)
    }
})


if (process.env.DISCORDJS_BOT_TOKEN_EMBED_LISTENER) {
    client.login(process.env.DISCORDJS_BOT_TOKEN_EMBED_LISTENER.toString());
    logger.info(`initialized client`, new Date())
}
else {
    logger.error(`No value of bot token, client failed to start`)
}
